name: Python application

on:
  workflow_call:
    inputs:
      apikey:
        description: 'Apikey'
        default: 'empty'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run app
      run: |
        python geo.py "Beverly Hills, CA" "90210" "12345" --appid ${{ inputs.apikey }}
    - name: Test with unittest
      run: |
        python -m unittest tests/geotests.py 
